version: '2'

services:

  bingo-app:
    build: ./bingo-app
    ports:
      - 8080:80

  bingo-server:
    build: ./bingo-server
    ports:
      - 3000:3000

  wifi-connect:
    build: ./wifi-connect
    network_mode: host
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: '1'

  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./balena-sound/bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth

volumes:
  spotifycache:
  bluetoothcache: