version: '2'

services:

  bingo-app:
    build: ./bingo-app
    ports:
      - 8080:80

  wifi-connect:
    build: ./wifi-connect
    network_mode: host
    privileged: true
    restart: always
    ports:
      - 8081:80
    labels:
      io.balena.features.dbus: '1'

  bluetooth-audio:
    network_mode: host
    restart: always
    build: ./balena-sound/bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
      
  spotify:
    build: ./balena-sound/spotify
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify

volumes:
  spotifycache:
  bluetoothcache: