###################
### BUILD STAGE ###
###################
FROM balenalib/%%BALENA_MACHINE_NAME%%-node:11-build
LABEL author "Tomás Migone"
LABEL maintainer "tomasmigone@gmail.com"

# Get code
WORKDIR /usr/src
COPY . .

# Compile it
RUN JOBS=MAX npm install
CMD npm run start
